[package]
name = "world-generation"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
geo.workspace = true
glam = "0.30.9"
noise = "0.9.0"
rand = "0.9.2"
smallvec = "1.15.1"
voronoice = "0.2.0"
tracing = "0.1"

helpers = {workspace = true}
